service: error-parsing

plugins:
  - serverless-python-requirements
  - serverless-plugin-aws-alerts

custom:
  logGroup: ${env:LOGGROUP}
  snsARN: "arn:aws:sns:${aws:region}:${aws:accountId}:${env:SNS_TOPIC_NAME}"

provider:
  name: aws
  runtime: python3.12
  stage: ${opt:stage, 'dev'}
  region: eu-west-3
  deploymentBucket:
    name: sls-deployments-${aws:accountId}-${self:provider.region}
    maxPreviousDeploymentArtifacts: 1
  environment:
    SNS_ARN: ${self:custom.snsARN}
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "sns:Publish"
      Resource:
        - "${self:custom.snsARN}"

functions:
  publish:
    handler: handler.run
    description: Parses errors and sends to SNS.
    timeout: 10
    events:
      - cloudwatchLog:
          logGroup: "${self:custom.logGroup}"
          filter: '"[ERROR]"'
