name: Serverless Remove

on: workflow_dispatch

jobs:
  sls-remove:
    name: Serverless Remove
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ github.workspace }}/serverless/
    strategy:
      matrix:
        node-version: [18.x]
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm shrinkwrap
      - run: npm ci
      - name: serverless install plugins
        uses: serverless/github-action@v3.2
        with:
          args: -c "cd ./serverless && serverless plugin install --name serverless-python-requirements && serverless plugin install --name serverless-plugin-aws-alerts"
          entrypoint: /bin/sh
      - name: serverless remove
        uses: serverless/github-action@v3.2
        with:
          args: -c "cd ./serverless && remove --stage ${{ env.CI_ENV }}"
          entrypoint: /bin/sh
        env:
          CI_ENV: prod
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          LOGGROUP: ${{ vars.LOGGROUP }}
          EMAIL: ${{ secrets.EMAIL }}
